dist: xenial
sudo: false
language: d

branches:
  only:
  - master

os:
  - linux
  - osx
d:
  - dmd
  - dmd-beta
  - dmd-nightly
  - ldc
  - ldc-beta
script:
  - dub build
  - dub test --build=unittest-cov
after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: ninja
      before_install:
        - sudo apt-get install python3-pip python3-setuptools
        - pip3 install 'meson==0.48.2'
      install:
        - mkdir .ntmp && curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
        - unzip .ntmp/ninja-linux.zip -d .ntmp
      before_script:
        - export PATH=$PATH:$PWD/.ntmp
      script:
        - meson build && ninja -j8 -C build
        - ninja -j8 -C build test -v
      after_success: skip
    - stage: dub examples
      script:
        - "dub build dyaml:benchmark"
        - "dub build dyaml:constructor"
        - "dub build dyaml:getting-started"
        - "dub build dyaml:representer"
        - "dub build dyaml:resolver"
        - "dub build dyaml:tojson"
        - "dub build dyaml:yaml_gen"
        - "dub build dyaml:yaml_stats"
      after_success: skip
...
